MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :session_token, :password_digest, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token

  def self.find_by_credentials(email, pw)
    user = User.find_by(email: email)
    return nil unless user
    user.is_password?(pw) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password
    @password
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    session[:session_token] = nil
    current_user.reset_session_token! if current_user
  end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new  # need to create this view
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] << "Invalid login credentials"
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <h1>Music App</h1>
    <% if logged_in? %>
      <%= button_to 'Logout', session_url, method: :delete %>
    <% else %>
      <%= link_to 'Sign Up', new_user_url %>
      <%= link_to 'Sign In', new_session_url %>
    <% end %>
    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <%= error %>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

MusicApp/app/views/users/new.html.erb
<h2>Create an Account</h2>
<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Email: 
    <input name="user[email]" value="<%= @user.email %>">
  </label>
  <br>
  <label>Password: 
    <input type="password" name="user[password]" value="<%= @user.password %>">
  </label>
  <br>
  <input type='submit' value="Create Account">
</form>

MusicApp/app/views/users/show.html.erb
<h2>Welcome, <%= @user.email %></h2>